/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Application = IDL.Record({
  'age' : IDL.Nat,
  'gameUsername' : IDL.Text,
  'message' : IDL.Text,
  'playerName' : IDL.Text,
});
export const SocialMediaLinks = IDL.Record({
  'tiktok' : IDL.Text,
  'twitter' : IDL.Text,
  'instagram' : IDL.Text,
  'discord' : IDL.Text,
  'youtube' : IDL.Text,
});

export const idlService = IDL.Service({
  'getApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getDiscordMemberCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSocialMediaLinks' : IDL.Func([], [SocialMediaLinks], ['query']),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateDiscordMemberCount' : IDL.Func([IDL.Nat], [], []),
  'updateSocialMediaLinks' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Application = IDL.Record({
    'age' : IDL.Nat,
    'gameUsername' : IDL.Text,
    'message' : IDL.Text,
    'playerName' : IDL.Text,
  });
  const SocialMediaLinks = IDL.Record({
    'tiktok' : IDL.Text,
    'twitter' : IDL.Text,
    'instagram' : IDL.Text,
    'discord' : IDL.Text,
    'youtube' : IDL.Text,
  });
  
  return IDL.Service({
    'getApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getDiscordMemberCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSocialMediaLinks' : IDL.Func([], [SocialMediaLinks], ['query']),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateDiscordMemberCount' : IDL.Func([IDL.Nat], [], []),
    'updateSocialMediaLinks' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };